/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Q3 IDE contributors. All rights reserved.
 *  Licensed under the MIT License.
 *--------------------------------------------------------------------------------------------*/

import { Disposable } from '../../../../base/common/lifecycle.js';
import { isWindows } from '../../../../base/common/platform.js';
import { InstantiationType, registerSingleton } from '../../../../platform/instantiation/common/extensions.js';
import { IConfigurationService } from '../../../../platform/configuration/common/configuration.js';
import { Emitter, Event } from '../../../../base/common/event.js';
import { ILogService } from '../../../../platform/log/common/log.js';
import { ITerminalService } from '../../../contrib/terminal/browser/terminal.js';
import { IFileService } from '../../../../platform/files/common/files.js';
import { VSBuffer } from '../../../../base/common/buffer.js';
import { URI } from '../../../../base/common/uri.js';
import { IQ3LlamaCppService } from './q3Agent.js';

export class Q3LlamaCppService extends Disposable implements IQ3LlamaCppService {
	declare readonly _serviceBrand: undefined;

	private _terminal: any | undefined;
	private _state: 'stopped' | 'starting' | 'running' | 'error' = 'stopped';

	private readonly _onDidStateChange = new Emitter<'stopped' | 'starting' | 'running' | 'error'>();
	readonly onDidStateChange: Event<'stopped' | 'starting' | 'running' | 'error'> = this._onDidStateChange.event;

	private readonly _onDidStatusMessage = new Emitter<string>();
	readonly onDidStatusMessage: Event<string> = this._onDidStatusMessage.event;

	public fireStatusMessage(msg: string): void {
		this._onDidStatusMessage.fire(msg);
	}

	constructor(
		@IConfigurationService private readonly _configService: IConfigurationService,
		@ILogService private readonly _logService: ILogService,
		@ITerminalService private readonly _terminalService: ITerminalService,
		@IFileService private readonly _fileService: IFileService,
	) {
		super();
		this._register({ dispose: () => this.stop() });
	}

	private _getLlamaSwapPath(): string {
		return this._configService.getValue<string>('q3.agent.llamacpp.llamaSwapPath') || '';
	}

	private _getServerBinaryPath(): string {
		return this._configService.getValue<string>('q3.agent.llamacpp.serverBinaryPath') || '';
	}

	isRunning(): boolean {
		return this._state === 'running';
	}

	getPort(): number {
		return this._configService.getValue<number>('q3.agent.llamacpp.port') || 8080;
	}

	getEndpoint(): string {
		return `http://127.0.0.1:${this.getPort()}`;
	}

	private _setState(state: 'stopped' | 'starting' | 'running' | 'error'): void {
		if (this._state !== state) {
			this._state = state;
			this._onDidStateChange.fire(state);
		}
	}

	private _getBinaryPath(): string {
		const customPath = this._configService.getValue<string>('q3.agent.llamacpp.binaryPath');
		if (customPath) {
			return customPath;
		}
		return '';
	}

	private _buildServerArgs(): string[] {
		const modelPath = this._configService.getValue<string>('q3.agent.llamacpp.modelPath');
		const ctxSize = this._configService.getValue<number>('q3.agent.llamacpp.ctxSize') || 32768;
		const kvCacheType = this._configService.getValue<string>('q3.agent.llamacpp.kvCacheType') || 'q8_0';
		const moeOffload = this._configService.getValue<boolean>('q3.agent.llamacpp.moeOffload') ?? false;
		const gpuLayers = this._configService.getValue<number>('q3.agent.llamacpp.gpuLayers') || 99;
		const model = this._configService.getValue<string>('q3.agent.model') || 'qwen3-coder:30b';

		const args: string[] = [
			'--model', `"${modelPath}"`,
			'--ctx-size', String(ctxSize),
			'--n-gpu-layers', String(gpuLayers),
			'--flash-attn', 'on',
			'--jinja',
			'--repeat-penalty', '1.05',
			'--repeat-last-n', '-1',
			'--temp', '0.7',
			'--top-p', '0.8',
			'--top-k', '20',
			'-np', '1',
			'--alias', model,
		];

		// KV cache quantization
		args.push('-ctk', kvCacheType, '-ctv', kvCacheType);

		// MoE expert offloading to CPU
		if (moeOffload) {
			args.push('-ot', '".ffn_.*_exps.=CPU"');
		}

		return args;
	}

	private _generateLlamaSwapConfig(): string | null {
		const serverBinary = this._getServerBinaryPath();
		const modelPath = this._configService.getValue<string>('q3.agent.llamacpp.modelPath');
		if (!serverBinary || !modelPath) { return null; }

		const ttl = this._configService.getValue<number>('q3.agent.llamacpp.ttl') || 300;
		const modelAlias = this._configService.getValue<string>('q3.agent.model') || 'qwen3-coder:30b';
		const serverArgs = this._buildServerArgs().join(' ');

		// YAML config for llama-swap — quote the model key (contains colon)
		const config = `# Auto-generated by Q3 IDE\nmodels:\n  "${modelAlias}":\n    cmd: '"${serverBinary}" ${serverArgs} --port \${PORT}'\n    ttl: ${ttl}\n`;
		return config;
	}

	async start(): Promise<boolean> {
		if (this.isRunning()) {
			return true;
		}

		const modelPath = this._configService.getValue<string>('q3.agent.llamacpp.modelPath');
		if (!modelPath) {
			this._logService.error('[Q3LlamaCpp] No model path configured');
			this._setState('error');
			return false;
		}

		// Check if llama-swap is already running from a previous session
		this._setState('starting');
		try {
			const endpoint = this.getEndpoint();
			this._logService.info('[Q3LlamaCpp] Checking if server already running at', endpoint);
			const resp = await fetch(`${endpoint}/v1/models`);
			this._logService.info('[Q3LlamaCpp] Pre-check got status', resp.status);
			if (resp.ok) {
				this._logService.info('[Q3LlamaCpp] Server already running, reusing');
				this._setState('running');
				return true;
			}
		} catch (err: any) {
			this._logService.info('[Q3LlamaCpp] Pre-check failed, server not running:', err?.message || err);
		}

		const llamaSwapPath = this._getLlamaSwapPath();
		const useSwap = llamaSwapPath !== '';

		if (useSwap) {
			return this._startWithLlamaSwap(llamaSwapPath);
		} else {
			return this._startDirect();
		}
	}

	private async _startWithLlamaSwap(llamaSwapPath: string): Promise<boolean> {
		this._logService.info('[Q3LlamaCpp] Starting via llama-swap:', llamaSwapPath);

		const configContent = this._generateLlamaSwapConfig();
		if (!configContent) {
			this._logService.error('[Q3LlamaCpp] Failed to generate llama-swap config');
			this._setState('error');
			return false;
		}

		// Write config file to .q3ide/llamacpp/llama-swap.yaml
		const configDir = this._getConfigDir();
		const configPath = `${configDir}\\llama-swap.yaml`;
		try {
			const configUri = URI.file(configPath);
			await this._fileService.writeFile(configUri, VSBuffer.fromString(configContent));
		} catch (err: any) {
			this._logService.error('[Q3LlamaCpp] Failed to write llama-swap config:', err);
			this._setState('error');
			return false;
		}

		const port = this.getPort();
		const swapDir = llamaSwapPath.substring(0, llamaSwapPath.lastIndexOf('\\'));
		const cmd = `& "${llamaSwapPath}" --config "${configPath}" -listen :${port}`;
		this._logService.info('[Q3LlamaCpp] Command:', cmd);

		try {
			this._terminal = await this._terminalService.createTerminal({ config: { name: 'Q3 LlamaCpp Server (llama-swap)', cwd: swapDir, isTransient: true } });
			this._terminalService.setActiveInstance(this._terminal);
			await new Promise(resolve => setTimeout(resolve, 1000));
			this._terminal.sendText(cmd, true);
		} catch (err: any) {
			this._logService.error('[Q3LlamaCpp] Failed to create terminal:', err);
			this._setState('error');
			return false;
		}

		// llama-swap starts fast, but the upstream llama-server takes time to load
		const ready = await this._waitForReady(300000);
		if (ready) {
			this._setState('running');
			this._logService.info('[Q3LlamaCpp] llama-swap is ready at', this.getEndpoint());
			return true;
		} else {
			this._logService.error('[Q3LlamaCpp] llama-swap failed to become ready within timeout');
			this._setState('error');
			return false;
		}
	}

	private async _startDirect(): Promise<boolean> {
		const binaryPath = this._getBinaryPath();
		if (!binaryPath) {
			this._logService.error('[Q3LlamaCpp] No llama-server binary path configured');
			this._setState('error');
			return false;
		}

		this._logService.info('[Q3LlamaCpp] Starting llama-server via terminal:', binaryPath);

		const args = this._buildServerArgs();
		const port = this.getPort();
		const binaryDir = binaryPath.substring(0, binaryPath.lastIndexOf('\\'));
		const cmd = `& "${binaryPath}" ${args.join(' ')} --port ${port}`;
		this._logService.info('[Q3LlamaCpp] Command:', cmd);

		try {
			this._terminal = await this._terminalService.createTerminal({ config: { name: 'Q3 LlamaCpp Server', cwd: binaryDir, isTransient: true } });
			this._terminalService.setActiveInstance(this._terminal);
			await new Promise(resolve => setTimeout(resolve, 1000));
			this._terminal.sendText(cmd, true);
		} catch (err: any) {
			this._logService.error('[Q3LlamaCpp] Failed to create terminal:', err);
			this._setState('error');
			return false;
		}

		const ready = await this._waitForReady(300000);
		if (ready) {
			this._setState('running');
			this._logService.info('[Q3LlamaCpp] Server is ready at', this.getEndpoint());
			return true;
		} else {
			this._logService.error('[Q3LlamaCpp] Server failed to become ready within timeout');
			this._setState('error');
			return false;
		}
	}

	private _getConfigDir(): string {
		try {
			const os = globalThis.require('os');
			const path = globalThis.require('path');
			const dir = path.join(os.homedir(), '.q3ide', 'llamacpp');
			return dir;
		} catch {
			return 'C:\\Users\\Ceete\\.q3ide\\llamacpp';
		}
	}

	private async _waitForReady(timeoutMs: number): Promise<boolean> {
		const startTime = Date.now();
		const endpoint = this.getEndpoint();
		let attempt = 0;

		while (Date.now() - startTime < timeoutMs) {
			if (this._state === 'error') {
				this._logService.error('[Q3LlamaCpp] _waitForReady aborted: state is error');
				return false;
			}

			attempt++;
			try {
				this._logService.info(`[Q3LlamaCpp] _waitForReady attempt ${attempt}, fetching ${endpoint}/v1/models`);
				const resp = await fetch(`${endpoint}/v1/models`);
				this._logService.info(`[Q3LlamaCpp] _waitForReady attempt ${attempt} got status ${resp.status}`);
				if (resp.ok) {
					this._logService.info('[Q3LlamaCpp] _waitForReady: server is ready!');
					return true;
				}
			} catch (err: any) {
				this._logService.warn(`[Q3LlamaCpp] _waitForReady attempt ${attempt} failed: ${err?.message || err}`);
				// Server not ready yet, continue polling
			}

			await this._sleep(1000);
		}

		this._logService.error('[Q3LlamaCpp] _waitForReady timed out');
		return false;
	}

	async stop(): Promise<void> {
		if (this._terminal) {
			this._logService.info('[Q3LlamaCpp] Stopping llama-server (sending Ctrl+C to terminal)');
			try {
				this._terminal.sendText('\x03', false);
			} catch {
				// Terminal may have already been disposed
			}
			this._terminal = undefined;
		}
		// Force-kill any lingering llama-swap and llama-server processes via terminal
		await this._killViaTerminal(
			isWindows
				? 'powershell -NoProfile -Command "Get-Process llama* -ErrorAction SilentlyContinue | Stop-Process -Force"'
				: 'pkill -f llama-swap; pkill -f llama-server'
		);
		this._setState('stopped');
	}

	private async _killViaTerminal(cmd: string): Promise<void> {
		try {
			const term = await this._terminalService.createTerminal({ config: { name: 'Q3 Kill', isTransient: true } });
			this._terminalService.setActiveInstance(term);
			// Wait for the terminal shell to be ready before sending text
			await new Promise(resolve => setTimeout(resolve, 1000));
			term.sendText(cmd, true);
			this._logService.info(`[Q3LlamaCpp] Kill command sent to terminal: ${cmd}`);
			// Give the command time to execute before disposing
			await new Promise(resolve => setTimeout(resolve, 3000));
			try { term.dispose(); } catch { }
		} catch (err: any) {
			this._logService.error('[Q3LlamaCpp] Failed to create kill terminal:', err);
		}
	}

	private _sleep(ms: number): Promise<void> {
		return new Promise(resolve => setTimeout(resolve, ms));
	}
}

registerSingleton(IQ3LlamaCppService, Q3LlamaCppService, InstantiationType.Delayed);
